# Generated by Django 5.0.4 on 2024-04-29 07:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_auth_status_alter_user_auth_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userconfirmation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifycode', to=settings.AUTH_USER_MODEL),
        ),
    ]
